// Generated local emoji search data. No internet/API needed.

// Every emoji shown in the keyboard gets Unicode-name keywords here.

const Map<String, String> emojiSearchIndex = {
  '😂': 'face tears joy laugh funny lol  ',
  '😭': 'loudly crying face  ',
  '🔥': 'fire fire lit hot flame burn cool hype ',
  '💀': 'skull dead skull death funny laughing meme dead ',
  '❤️': 'heavy black heart love heart red heart romance romantic crush care affection like ',
  '👍': 'thumbs up like yes okay approve  ',
  '🥲': 'smiling face with tear  ',
  '😤': 'face with look of triumph  ',
  '👀': 'eyes  ',
  '🙏': 'folded hands pray please thanks namaste  ',
  '🗿': 'moyai sigma moyai moai stone face meme statue serious deadpan gigachad ',
  '😀': 'grinning face  ',
  '😃': 'smiling face with open mouth  ',
  '😄': 'smiling face with open mouth and smiling eyes  ',
  '😁': 'grinning face with smiling eyes  ',
  '😆': 'smiling face with open mouth and tightly closed eyes  ',
  '😅': 'smiling face with open mouth and cold sweat  ',
  '🤣': 'rolling on the floor laughing  ',
  '🙂': 'slightly smiling face  ',
  '🙃': 'upside down face  ',
  '🫠': 'melting face  ',
  '😉': 'winking face  ',
  '😊': 'smiling face with smiling eyes  ',
  '😇': 'smiling face with halo  ',
  '🥰': 'smiling face with smiling eyes and three hearts love smiling hearts cute affection ',
  '😍': 'smiling face with heart shaped eyes love heart eyes crush cute romance ',
  '🤩': 'grinning face with star eyes  ',
  '😘': 'face throwing a kiss love kiss heart romance ',
  '😗': 'kissing face  ',
  '☺️': 'white smiling face  ',
  '😚': 'kissing face with closed eyes  ',
  '😙': 'kissing face with smiling eyes  ',
  '😋': 'face savouring delicious food  ',
  '😛': 'face with stuck out tongue  ',
  '😜': 'face with stuck out tongue and winking eye  ',
  '🤪': 'grinning face with one large and one small eye  ',
  '😝': 'face with stuck out tongue and tightly closed eyes  ',
  '🤑': 'money mouth face money rich cash face greed ',
  '🤗': 'hugging face  ',
  '🤭': 'smiling face with smiling eyes and hand covering mouth  ',
  '🫢': 'face with open eyes and hand over mouth  ',
  '🫣': 'face with peeking eye  ',
  '🤫': 'face with finger covering closed lips sigma shush quiet secret mewing meme ',
  '🤔': 'thinking face  ',
  '🫡': 'saluting face  ',
  '🤐': 'zipper mouth face  ',
  '🤨': 'face with one eyebrow raised  ',
  '😐': 'neutral face  ',
  '😑': 'expressionless face  ',
  '😶': 'face without mouth  ',
  '🫥': 'dotted line face  ',
  '😏': 'smirking face  ',
  '😒': 'unamused face  ',
  '🙄': 'face with rolling eyes  ',
  '😬': 'grimacing face  ',
  '😮‍💨': 'face with open mouth dash symbol  ',
  '🤥': 'lying face  ',
  '😌': 'relieved face  ',
  '😔': 'pensive face  ',
  '😪': 'sleepy face  ',
  '🤤': 'drooling face  ',
  '😴': 'sleeping face  ',
  '😷': 'face with medical mask  ',
  '🤒': 'face with thermometer  ',
  '🤕': 'face with head bandage  ',
  '🤢': 'nauseated face  ',
  '🤮': 'face with open mouth vomiting  ',
  '🤧': 'sneezing face  ',
  '🥵': 'overheated face  ',
  '🥶': 'freezing face  ',
  '🥴': 'face with uneven eyes and wavy mouth  ',
  '😵': 'dizzy face  ',
  '😵‍💫': 'dizzy face dizzy symbol  ',
  '🤯': 'shocked face with exploding head  ',
  '🤠': 'face with cowboy hat  ',
  '🥳': 'face with party horn and party hat party partying celebration birthday happy excited woohoo ',
  '🥸': 'disguised face  ',
  '😎': 'smiling face with sunglasses  ',
  '🤓': 'nerd face  ',
  '🧐': 'face with monocle  ',
  '😕': 'confused face  ',
  '🫤': 'face with diagonal mouth  ',
  '😟': 'worried face  ',
  '🙁': 'slightly frowning face  ',
  '☹️': 'white frowning face  ',
  '😮': 'face with open mouth  ',
  '😯': 'hushed face  ',
  '😲': 'astonished face  ',
  '😳': 'flushed face  ',
  '🥺': 'face with pleading eyes  ',
  '🥹': 'face holding back tears  ',
  '😦': 'frowning face with open mouth  ',
  '😧': 'anguished face  ',
  '😨': 'fearful face  ',
  '😰': 'face with open mouth and cold sweat  ',
  '😥': 'disappointed but relieved face  ',
  '😢': 'crying face  ',
  '😱': 'face screaming in fear  ',
  '😖': 'confounded face  ',
  '😣': 'persevering face  ',
  '😞': 'disappointed face  ',
  '😓': 'face with cold sweat  ',
  '😩': 'weary face  ',
  '😫': 'tired face  ',
  '🥱': 'yawning face  ',
  '😡': 'pouting face  ',
  '😠': 'angry face  ',
  '🤬': 'serious face with symbols covering mouth  ',
  '😈': 'smiling face with horns  ',
  '👿': 'imp  ',
  '☠️': 'skull and crossbones dead skull poison danger death pirate ',
  '💩': 'pile of poo  ',
  '🤡': 'clown face  ',
  '👹': 'japanese ogre  ',
  '👺': 'japanese goblin  ',
  '👻': 'ghost  ',
  '👽': 'extraterrestrial alien  ',
  '👾': 'alien monster  ',
  '🤖': 'robot face  ',
  '😶‍🌫️': 'face without mouth fog  ',
  '🙂‍↔️': 'slightly smiling face left right arrow  ',
  '🙂‍↕️': 'slightly smiling face up down arrow  ',
  '😺': 'smiling cat face with open mouth  ',
  '😸': 'grinning cat face with smiling eyes  ',
  '😹': 'cat face tears joy laugh funny lol  ',
  '😻': 'smiling cat face with heart shaped eyes  ',
  '😼': 'cat face with wry smile  ',
  '😽': 'kissing cat face with closed eyes  ',
  '🙀': 'weary cat face  ',
  '😿': 'crying cat face  ',
  '😾': 'pouting cat face  ',
  '👋': 'waving hand sign  ',
  '🤚': 'raised back of hand  ',
  '🖐': 'raised hand with fingers splayed  ',
  '🖖': 'raised hand with part between middle and ring fingers  ',
  '🫱': 'rightwards hand  ',
  '🫲': 'leftwards hand  ',
  '🫳': 'palm down hand  ',
  '🫴': 'palm up hand  ',
  '👌': 'ok hand sign  ',
  '🤌': 'pinched fingers  ',
  '🤏': 'pinching hand  ',
  '🤞': 'hand with index and middle fingers crossed  ',
  '🫰': 'hand with index finger and thumb crossed  ',
  '🤟': 'i love you hand sign  ',
  '🤘': 'sign of the horns  ',
  '🤙': 'call me hand  ',
  '👈': 'white left pointing backhand index  ',
  '👉': 'white right pointing backhand index  ',
  '👆': 'white up pointing backhand index  ',
  '🖕': 'reversed hand with middle finger extended  ',
  '👇': 'white down pointing backhand index  ',
  '👎': 'thumbs down dislike no reject  ',
  '👊': 'fisted hand sign  ',
  '🤛': 'left facing fist  ',
  '🤜': 'right facing fist  ',
  '👏': 'clapping hands sign  ',
  '🙌': 'person raising both hands in celebration  ',
  '🫶': 'heart hands  ',
  '👐': 'open hands sign  ',
  '🤲': 'palms up together  ',
  '🤝': 'handshake  ',
  '💅': 'nail polish  ',
  '🤳': 'selfie  ',
  '💪': 'flexed biceps  ',
  '🦵': 'leg  ',
  '🦶': 'foot  ',
  '👂': 'ear  ',
  '🦻': 'ear with hearing aid  ',
  '👃': 'nose  ',
  '🧠': 'brain  ',
  '🫀': 'anatomical heart  ',
  '🫁': 'lungs  ',
  '🦷': 'tooth  ',
  '🦴': 'bone  ',
  '👁': 'eye  ',
  '👅': 'tongue  ',
  '👄': 'mouth  ',
  '🫦': 'biting lip  ',
  '👶': 'baby  ',
  '🧒': 'child  ',
  '👦': 'boy  ',
  '👧': 'girl  ',
  '🧑': 'adult  ',
  '👨': 'man  ',
  '👩': 'woman  ',
  '🧔': 'bearded person  ',
  '👱': 'person with blond hair  ',
  '👴': 'older man  ',
  '👵': 'older woman  ',
  '🙍': 'person frowning  ',
  '🙎': 'person with pouting face  ',
  '🙅': 'face with no good gesture  ',
  '🙆': 'face with ok gesture  ',
  '💁': 'information desk person  ',
  '🙋': 'happy person raising one hand  ',
  '🧏': 'deaf person sigma deaf mewing meme listen ',
  '🙇': 'person bowing deeply  ',
  '🤦': 'face palm  ',
  '🤷': 'shrug  ',
  '🧑‍⚕️': 'adult staff of aesculapius  ',
  '🧑‍🎓': 'adult graduation cap  ',
  '🧑‍🏫': 'adult school  ',
  '🧑‍⚖️': 'adult scales  ',
  '🧑‍🌾': 'adult ear of rice  ',
  '🧑‍🍳': 'adult cooking  ',
  '🧑‍🔧': 'adult wrench  ',
  '🧑‍🏭': 'adult factory  ',
  '🧑‍💼': 'adult briefcase  ',
  '🧑‍🔬': 'adult microscope  ',
  '🧑‍💻': 'adult personal computer  ',
  '🧑‍🎤': 'adult microphone  ',
  '🧑‍🎨': 'adult artist palette  ',
  '🧑‍✈️': 'adult airplane  ',
  '🧑‍🚀': 'adult rocket  ',
  '🧑‍🚒': 'adult fire engine  ',
  '👮': 'police officer  ',
  '🕵': 'sleuth or spy  ',
  '💂': 'guardsman  ',
  '🥷': 'ninja  ',
  '👷': 'construction worker  ',
  '🫅': 'person with crown  ',
  '🤴': 'prince  ',
  '👸': 'princess  ',
  '👳': 'man with turban  ',
  '👲': 'man with gua pi mao  ',
  '🧕': 'person with headscarf  ',
  '🤵': 'man in tuxedo  ',
  '👰': 'bride with veil  ',
  '🤰': 'pregnant woman  ',
  '🫃': 'pregnant man  ',
  '🫄': 'pregnant person  ',
  '👩‍🍼': 'woman baby bottle  ',
  '🧑‍🍼': 'adult baby bottle  ',
  '👨‍🍼': 'man baby bottle  ',
  '🧙': 'mage  ',
  '🧚': 'fairy  ',
  '🧛': 'vampire  ',
  '🧜': 'merperson  ',
  '🧝': 'elf  ',
  '🧞': 'genie  ',
  '🧟': 'zombie  ',
  '💆': 'face massage  ',
  '💇': 'haircut  ',
  '🚶': 'pedestrian  ',
  '🧍': 'standing person  ',
  '🧎': 'kneeling person  ',
  '🏃': 'runner  ',
  '💃': 'dancer  ',
  '🕺': 'man dancing  ',
  '🕴': 'man in business suit levitating  ',
  '👯': 'woman with bunny ears  ',
  '🧖': 'person in steamy room  ',
  '🧗': 'person climbing  ',
  '🤺': 'fencer  ',
  '🏇': 'horse racing  ',
  '🏂': 'snowboarder  ',
  '🏌': 'golfer  ',
  '🏄': 'surfer  ',
  '🚣': 'rowboat  ',
  '🏊': 'swimmer  ',
  '🏋': 'weight lifter  ',
  '🚴': 'bicyclist  ',
  '🚵': 'mountain bicyclist  ',
  '🤸': 'person doing cartwheel  ',
  '🤼': 'wrestlers  ',
  '🤽': 'water polo  ',
  '🤾': 'handball  ',
  '🤹': 'juggling  ',
  '🧘': 'person in lotus position  ',
  '🛀': 'bath  ',
  '🛌': 'sleeping accommodation  ',
  '👫': 'man and woman holding hands  ',
  '👬': 'two men holding hands  ',
  '👭': 'two women holding hands  ',
  '💏': 'kiss  ',
  '💑': 'couple with heart  ',
  '👨‍👩‍👧': 'man woman girl  ',
  '👨‍👩‍👦': 'man woman boy  ',
  '👩‍👩‍👧': 'woman woman girl  ',
  '👨‍👨‍👦': 'man man boy  ',
  '👪': 'family  ',
  '🗣': 'speaking head in silhouette  ',
  '👤': 'bust in silhouette  ',
  '👥': 'busts in silhouette  ',
  '🫂': 'people hugging  ',
  '👣': 'footprints  ',
  '🐶': 'dog face  ',
  '🐱': 'cat face  ',
  '🐭': 'mouse face  ',
  '🐹': 'hamster face  ',
  '🐰': 'rabbit face  ',
  '🦊': 'fox face  ',
  '🐻': 'bear face  ',
  '🐼': 'panda face  ',
  '🐻‍❄️': 'bear face snowflake  ',
  '🐨': 'koala  ',
  '🐯': 'tiger face  ',
  '🦁': 'lion face  ',
  '🐮': 'cow face  ',
  '🐷': 'pig face  ',
  '🐽': 'pig nose  ',
  '🐸': 'frog face  ',
  '🐵': 'monkey face  ',
  '🙈': 'see no evil monkey  ',
  '🙉': 'hear no evil monkey  ',
  '🙊': 'speak no evil monkey  ',
  '🐒': 'monkey  ',
  '🐔': 'chicken  ',
  '🐧': 'penguin  ',
  '🐦': 'bird  ',
  '🐤': 'baby chick  ',
  '🐣': 'hatching chick  ',
  '🐥': 'front facing baby chick  ',
  '🦆': 'duck  ',
  '🦅': 'eagle  ',
  '🦉': 'owl  ',
  '🦇': 'bat  ',
  '🐺': 'wolf face  ',
  '🐗': 'boar  ',
  '🐴': 'horse face  ',
  '🦄': 'unicorn face  ',
  '🐝': 'honeybee  ',
  '🪱': 'worm  ',
  '🐛': 'bug  ',
  '🦋': 'butterfly  ',
  '🐌': 'snail  ',
  '🐞': 'lady beetle  ',
  '🐜': 'ant  ',
  '🪰': 'fly  ',
  '🪲': 'beetle  ',
  '🪳': 'cockroach  ',
  '🦟': 'mosquito  ',
  '🦗': 'cricket  ',
  '🕷️': 'spider  ',
  '🦂': 'scorpion  ',
  '🐢': 'turtle  ',
  '🐍': 'snake  ',
  '🦎': 'lizard  ',
  '🦖': 't rex  ',
  '🦕': 'sauropod  ',
  '🐙': 'octopus  ',
  '🦑': 'squid  ',
  '🦐': 'shrimp  ',
  '🦞': 'lobster  ',
  '🦀': 'crab  ',
  '🐡': 'blowfish  ',
  '🐠': 'tropical fish  ',
  '🐟': 'fish  ',
  '🐬': 'dolphin  ',
  '🐳': 'spouting whale  ',
  '🐋': 'whale  ',
  '🦈': 'shark  ',
  '🐊': 'crocodile  ',
  '🐅': 'tiger  ',
  '🐆': 'leopard  ',
  '🦓': 'zebra face  ',
  '🦍': 'gorilla  ',
  '🦧': 'orangutan  ',
  '🦣': 'mammoth  ',
  '🐘': 'elephant  ',
  '🦏': 'rhinoceros  ',
  '🦛': 'hippopotamus  ',
  '🐪': 'dromedary camel  ',
  '🐫': 'bactrian camel  ',
  '🦒': 'giraffe face  ',
  '🦘': 'kangaroo  ',
  '🦬': 'bison  ',
  '🐃': 'water buffalo  ',
  '🐂': 'ox  ',
  '🐄': 'cow  ',
  '🐎': 'horse  ',
  '🐖': 'pig  ',
  '🐏': 'ram  ',
  '🐑': 'sheep  ',
  '🦙': 'llama  ',
  '🐐': 'goat  ',
  '🦌': 'deer  ',
  '🐕': 'dog  ',
  '🐩': 'poodle  ',
  '🦮': 'guide dog  ',
  '🐕‍🦺': 'dog safety vest  ',
  '🐈': 'cat  ',
  '🐈‍⬛': 'cat black large square  ',
  '🪶': 'feather  ',
  '🐓': 'rooster  ',
  '🦃': 'turkey  ',
  '🦤': 'dodo  ',
  '🦚': 'peacock  ',
  '🦜': 'parrot  ',
  '🦢': 'swan  ',
  '🦩': 'flamingo  ',
  '🕊️': 'dove of peace  ',
  '🐇': 'rabbit  ',
  '🦝': 'raccoon  ',
  '🦨': 'skunk  ',
  '🦡': 'badger  ',
  '🦫': 'beaver  ',
  '🦦': 'otter  ',
  '🦥': 'sloth  ',
  '🐁': 'mouse  ',
  '🐀': 'rat  ',
  '🐿️': 'chipmunk  ',
  '🦔': 'hedgehog  ',
  '🍏': 'green apple  ',
  '🍎': 'red apple  ',
  '🍐': 'pear  ',
  '🍊': 'tangerine  ',
  '🍋': 'lemon  ',
  '🍋‍🟩': 'lemon large green square  ',
  '🍌': 'banana  ',
  '🍉': 'watermelon  ',
  '🍇': 'grapes  ',
  '🍓': 'strawberry  ',
  '🫐': 'blueberries  ',
  '🍈': 'melon  ',
  '🍒': 'cherries  ',
  '🍑': 'peach  ',
  '🥭': 'mango  ',
  '🍍': 'pineapple  ',
  '🥥': 'coconut  ',
  '🥝': 'kiwifruit  ',
  '🍅': 'tomato  ',
  '🍆': 'aubergine  ',
  '🥑': 'avocado  ',
  '🫛': 'pea pod  ',
  '🥦': 'broccoli  ',
  '🥬': 'leafy green  ',
  '🥒': 'cucumber  ',
  '🌶️': 'hot pepper  ',
  '🫑': 'bell pepper  ',
  '🌽': 'ear of maize  ',
  '🥕': 'carrot  ',
  '🫒': 'olive  ',
  '🧄': 'garlic  ',
  '🧅': 'onion  ',
  '🥔': 'potato  ',
  '🍠': 'roasted sweet potato  ',
  '🫚': 'ginger root  ',
  '🥐': 'croissant  ',
  '🥯': 'bagel  ',
  '🍞': 'bread  ',
  '🥖': 'baguette bread  ',
  '🥨': 'pretzel  ',
  '🧀': 'cheese wedge  ',
  '🥚': 'egg  ',
  '🍳': 'cooking  ',
  '🧈': 'butter  ',
  '🥞': 'pancakes  ',
  '🧇': 'waffle  ',
  '🥓': 'bacon  ',
  '🥩': 'cut of meat  ',
  '🍗': 'poultry leg  ',
  '🍖': 'meat on bone  ',
  '🌭': 'hot dog  ',
  '🍔': 'hamburger  ',
  '🍟': 'french fries  ',
  '🍕': 'slice of pizza  ',
  '🫓': 'flatbread  ',
  '🥪': 'sandwich  ',
  '🥙': 'stuffed flatbread  ',
  '🧆': 'falafel  ',
  '🌮': 'taco  ',
  '🌯': 'burrito  ',
  '🫔': 'tamale  ',
  '🥗': 'green salad  ',
  '🥘': 'shallow pan of food  ',
  '🫕': 'fondue  ',
  '🥫': 'canned food  ',
  '🍝': 'spaghetti  ',
  '🍜': 'steaming bowl  ',
  '🍲': 'pot of food  ',
  '🍛': 'curry and rice  ',
  '🍣': 'sushi  ',
  '🍱': 'bento box  ',
  '🥟': 'dumpling  ',
  '🦪': 'oyster  ',
  '🍤': 'fried shrimp  ',
  '🍙': 'rice ball  ',
  '🍚': 'cooked rice  ',
  '🍘': 'rice cracker  ',
  '🍥': 'fish cake with swirl design  ',
  '🥠': 'fortune cookie  ',
  '🥮': 'moon cake  ',
  '🍢': 'oden  ',
  '🍡': 'dango  ',
  '🍧': 'shaved ice  ',
  '🍨': 'ice cream  ',
  '🍦': 'soft ice cream  ',
  '🥧': 'pie  ',
  '🧁': 'cupcake  ',
  '🍰': 'shortcake  ',
  '🎂': 'birthday cake party birthday cake celebration anniversary ',
  '🍮': 'custard  ',
  '🍭': 'lollipop  ',
  '🍬': 'candy  ',
  '🍫': 'chocolate bar  ',
  '🍿': 'popcorn  ',
  '🍩': 'doughnut  ',
  '🍪': 'cookie  ',
  '🌰': 'chestnut  ',
  '🥜': 'peanuts  ',
  '🫘': 'beans  ',
  '🍯': 'honey pot  ',
  '🥛': 'glass of milk  ',
  '🍼': 'baby bottle  ',
  '🫖': 'teapot  ',
  '🍵': 'teacup without handle  ',
  '🧃': 'beverage box  ',
  '🥤': 'cup with straw  ',
  '🧋': 'bubble tea  ',
  '🧉': 'mate drink  ',
  '🧊': 'ice cube  ',
  '🥢': 'chopsticks  ',
  '🍽️': 'fork and knife with plate  ',
  '🍴': 'fork and knife  ',
  '🥄': 'spoon  ',
  '🌍': 'earth globe europe africa  ',
  '🌎': 'earth globe americas  ',
  '🌏': 'earth globe asia australia  ',
  '🌐': 'globe with meridians  ',
  '🗺️': 'world map  ',
  '🧭': 'compass  ',
  '🏔️': 'snow capped mountain  ',
  '⛰️': 'mountain  ',
  '🌋': 'volcano  ',
  '🗻': 'mount fuji  ',
  '🏕️': 'camping  ',
  '🏖️': 'beach with umbrella  ',
  '🏜️': 'desert  ',
  '🏝️': 'desert island  ',
  '🏞️': 'national park  ',
  '🏟️': 'stadium  ',
  '🏛️': 'classical building  ',
  '🏗️': 'building construction  ',
  '🧱': 'brick  ',
  '🪨': 'rock  ',
  '🪵': 'wood  ',
  '🛖': 'hut  ',
  '🏘️': 'house buildings  ',
  '🏚️': 'derelict house building  ',
  '🏠': 'house building  ',
  '🏡': 'house with garden  ',
  '🏢': 'office building  ',
  '🏣': 'japanese post office  ',
  '🏤': 'european post office  ',
  '🏥': 'hospital  ',
  '🏦': 'bank money bank finance building ',
  '🏨': 'hotel  ',
  '🏪': 'convenience store  ',
  '🏫': 'school  ',
  '🏬': 'department store  ',
  '🏭': 'factory  ',
  '🏯': 'japanese castle  ',
  '🏰': 'european castle  ',
  '💒': 'wedding  ',
  '🗼': 'tokyo tower  ',
  '🗽': 'statue of liberty statue liberty statue of liberty new york usa america landmark monument travel ',
  '🕌': 'mosque  ',
  '🛕': 'hindu temple  ',
  '🕍': 'synagogue  ',
  '⛩️': 'shinto shrine  ',
  '🕋': 'kaaba  ',
  '🌁': 'foggy  ',
  '🌃': 'night with stars  ',
  '🏙️': 'cityscape  ',
  '🌄': 'sunrise over mountains  ',
  '🌅': 'sunrise  ',
  '🌆': 'cityscape at dusk  ',
  '🌇': 'sunset over buildings  ',
  '🌉': 'bridge at night  ',
  '♨️': 'hot springs  ',
  '🎠': 'carousel horse  ',
  '🛝': 'playground slide  ',
  '🎡': 'ferris wheel  ',
  '🎢': 'roller coaster  ',
  '💈': 'barber pole  ',
  '🎪': 'circus tent  ',
  '🚂': 'steam locomotive  ',
  '🚃': 'railway car  ',
  '🚄': 'high speed train  ',
  '🚅': 'high speed train with bullet nose  ',
  '🚆': 'train  ',
  '🚇': 'metro  ',
  '🚈': 'light rail  ',
  '🚉': 'station  ',
  '🚊': 'tram  ',
  '🚝': 'monorail  ',
  '🚞': 'mountain railway  ',
  '🚋': 'tram car  ',
  '🚌': 'bus  ',
  '🚍': 'oncoming bus  ',
  '🚎': 'trolleybus  ',
  '🚐': 'minibus  ',
  '🚑': 'ambulance  ',
  '🚒': 'fire engine  ',
  '🚓': 'police car  ',
  '🚔': 'oncoming police car  ',
  '🚕': 'taxi  ',
  '🚖': 'oncoming taxi  ',
  '🚗': 'automobile  ',
  '🚘': 'oncoming automobile  ',
  '🚙': 'recreational vehicle  ',
  '🛻': 'pickup truck  ',
  '🚚': 'delivery truck  ',
  '🚛': 'articulated lorry  ',
  '🚜': 'tractor  ',
  '🏎️': 'racing car  ',
  '🏍️': 'racing motorcycle  ',
  '🛵': 'motor scooter  ',
  '🦽': 'manual wheelchair  ',
  '🦼': 'motorized wheelchair  ',
  '🛺': 'auto rickshaw  ',
  '🚲': 'bicycle  ',
  '🛴': 'scooter  ',
  '🛹': 'skateboard  ',
  '🛼': 'roller skate  ',
  '🚏': 'bus stop  ',
  '🛣️': 'motorway  ',
  '🛤️': 'railway track  ',
  '🛢️': 'oil drum  ',
  '🛞': 'wheel  ',
  '🚨': 'police cars revolving light  ',
  '🚥': 'horizontal traffic light  ',
  '🚦': 'vertical traffic light  ',
  '🛑': 'octagonal sign  ',
  '🚧': 'construction sign  ',
  '🛟': 'ring buoy  ',
  '🛶': 'canoe  ',
  '🚤': 'speedboat  ',
  '🛳️': 'passenger ship  ',
  '⛴️': 'ferry  ',
  '🛥️': 'motor boat  ',
  '🚢': 'ship  ',
  '✈️': 'airplane  ',
  '🛩️': 'small airplane  ',
  '🛫': 'airplane departure  ',
  '🛬': 'airplane arriving  ',
  '🪂': 'parachute  ',
  '💺': 'seat  ',
  '🚁': 'helicopter  ',
  '🚟': 'suspension railway  ',
  '🚠': 'mountain cableway  ',
  '🚡': 'aerial tramway  ',
  '🛰️': 'satellite  ',
  '🚀': 'rocket  ',
  '🛸': 'flying saucer  ',
  '⚽': 'soccer ball  ',
  '🏀': 'basketball and hoop  ',
  '🏈': 'american football  ',
  '⚾': 'baseball  ',
  '🥎': 'softball  ',
  '🎾': 'tennis racquet and ball  ',
  '🏐': 'volleyball  ',
  '🏉': 'rugby football  ',
  '🥏': 'flying disc  ',
  '🎱': 'billiards  ',
  '🪀': 'yo yo  ',
  '🏓': 'table tennis paddle and ball  ',
  '🏸': 'badminton racquet and shuttlecock  ',
  '🏒': 'ice hockey stick and puck  ',
  '🏑': 'field hockey stick and ball  ',
  '🥍': 'lacrosse stick and ball  ',
  '🏏': 'cricket bat and ball  ',
  '🪃': 'boomerang  ',
  '🥅': 'goal net  ',
  '🪁': 'kite  ',
  '🏹': 'bow and arrow  ',
  '🎣': 'fishing pole and fish  ',
  '🤿': 'diving mask  ',
  '🥊': 'boxing glove  ',
  '🥋': 'martial arts uniform  ',
  '🎽': 'running shirt with sash  ',
  '🛷': 'sled  ',
  '⛸️': 'ice skate  ',
  '🥌': 'curling stone  ',
  '🎿': 'ski and ski boot  ',
  '⛷️': 'skier  ',
  '🏋️': 'weight lifter  ',
  '⛹️': 'person with ball  ',
  '🏌️': 'golfer  ',
  '🏆': 'trophy  ',
  '🥇': 'first place medal  ',
  '🥈': 'second place medal  ',
  '🥉': 'third place medal  ',
  '🏅': 'sports medal  ',
  '🎖️': 'military medal  ',
  '🏵️': 'rosette  ',
  '🎗️': 'reminder ribbon  ',
  '🎫': 'ticket  ',
  '🎟️': 'admission tickets  ',
  '🎭': 'performing arts  ',
  '🩰': 'ballet shoes  ',
  '🎨': 'artist palette  ',
  '🎬': 'clapper board  ',
  '🎤': 'microphone  ',
  '🎧': 'headphone  ',
  '🎼': 'musical score  ',
  '🎹': 'musical keyboard  ',
  '🥁': 'drum with drumsticks  ',
  '🪘': 'long drum  ',
  '🎷': 'saxophone  ',
  '🎺': 'trumpet  ',
  '🪗': 'accordion  ',
  '🎸': 'guitar  ',
  '🪕': 'banjo  ',
  '🎻': 'violin  ',
  '🪈': 'flute  ',
  '🎲': 'game die  ',
  '♟️': 'black chess pawn  ',
  '🎯': 'direct hit  ',
  '🎳': 'bowling  ',
  '🎮': 'video game  ',
  '🎰': 'slot machine  ',
  '🧩': 'jigsaw puzzle piece  ',
  '⌚': 'watch  ',
  '📱': 'mobile phone  ',
  '📲': 'mobile phone with rightwards arrow at left  ',
  '💻': 'personal computer  ',
  '⌨️': 'keyboard  ',
  '🖥️': 'desktop computer  ',
  '🖨️': 'printer  ',
  '🖱️': 'three button mouse  ',
  '🖲️': 'trackball  ',
  '🕹️': 'joystick  ',
  '🗜️': 'compression  ',
  '💽': 'minidisc  ',
  '💾': 'floppy disk  ',
  '💿': 'optical disc  ',
  '📀': 'dvd  ',
  '📼': 'videocassette  ',
  '📷': 'camera  ',
  '📸': 'camera with flash  ',
  '📹': 'video camera  ',
  '🎥': 'movie camera  ',
  '📽️': 'film projector  ',
  '🎞️': 'film frames  ',
  '📞': 'telephone receiver  ',
  '☎️': 'black telephone  ',
  '📟': 'pager  ',
  '📠': 'fax machine  ',
  '📺': 'television  ',
  '📻': 'radio  ',
  '🎙️': 'studio microphone  ',
  '🎚️': 'level slider  ',
  '🎛️': 'control knobs  ',
  '⏱️': 'stopwatch  ',
  '⏲️': 'timer clock  ',
  '🕰️': 'mantelpiece clock  ',
  '⌛': 'hourglass  ',
  '⏳': 'hourglass with flowing sand  ',
  '📡': 'satellite antenna  ',
  '🔋': 'battery  ',
  '🪫': 'low battery  ',
  '🔌': 'electric plug  ',
  '💡': 'electric light bulb  ',
  '🔦': 'electric torch  ',
  '🕯️': 'candle  ',
  '🪔': 'diya lamp  ',
  '🧯': 'fire extinguisher  ',
  '💸': 'money with wings money cash flying money spend payment ',
  '💵': 'banknote with dollar sign  ',
  '💴': 'banknote with yen sign  ',
  '💶': 'banknote with euro sign  ',
  '💷': 'banknote with pound sign  ',
  '🪙': 'coin  ',
  '💰': 'money bag money cash rich bag wealth payment ',
  '💳': 'credit card money card credit payment bank ',
  '🪪': 'identification card  ',
  '💎': 'gem stone  ',
  '⚖️': 'scales  ',
  '🪜': 'ladder  ',
  '🧰': 'toolbox  ',
  '🪛': 'screwdriver  ',
  '🔧': 'wrench  ',
  '🔨': 'hammer  ',
  '⚒️': 'hammer and pick  ',
  '🛠️': 'hammer and wrench  ',
  '⛏️': 'pick  ',
  '🪚': 'carpentry saw  ',
  '🔩': 'nut and bolt  ',
  '⚙️': 'gear  ',
  '🪤': 'mouse trap  ',
  '⛓️': 'chains  ',
  '🧲': 'magnet  ',
  '🪝': 'hook  ',
  '🧪': 'test tube  ',
  '🧫': 'petri dish  ',
  '🧬': 'dna double helix  ',
  '🔬': 'microscope  ',
  '🔭': 'telescope  ',
  '📿': 'prayer beads  ',
  '🧿': 'nazar amulet  ',
  '🔮': 'crystal ball  ',
  '🪬': 'hamsa  ',
  '⚗️': 'alembic  ',
  '🕳️': 'hole  ',
  '🩹': 'adhesive bandage  ',
  '🩺': 'stethoscope  ',
  '💊': 'pill  ',
  '💉': 'syringe  ',
  '🩸': 'drop of blood  ',
  '🧸': 'teddy bear  ',
  '🪆': 'nesting dolls  ',
  '🖼️': 'frame with picture  ',
  '🪞': 'mirror  ',
  '🪟': 'window  ',
  '🛍️': 'shopping bags  ',
  '🛒': 'shopping trolley  ',
  '🎁': 'gift present birthday party party gift present birthday surprise celebration ',
  '🎈': 'balloon party balloon birthday celebration decoration ',
  '🎏': 'carp streamer  ',
  '🎀': 'ribbon  ',
  '🪄': 'magic wand  ',
  '🪅': 'pinata  ',
  '🪩': 'mirror ball party disco dance nightclub music celebration ',
  '🎊': 'confetti ball party celebration confetti ball congratulations congrats festival ',
  '🎉': 'party popper celebration confetti party celebration confetti congratulations congrats yay fun festival birthday ',
  '🎎': 'japanese dolls  ',
  '🏮': 'izakaya lantern  ',
  '🎐': 'wind chime  ',
  '🧧': 'red gift envelope  ',
  '✉️': 'envelope  ',
  '📩': 'envelope with downwards arrow above  ',
  '📨': 'incoming envelope  ',
  '📧': 'e mail symbol  ',
  '💌': 'love letter love letter romance message valentine ',
  '📥': 'inbox tray  ',
  '📤': 'outbox tray  ',
  '📦': 'package  ',
  '🏷️': 'label  ',
  '📪': 'closed mailbox with lowered flag  ',
  '📫': 'closed mailbox with raised flag  ',
  '📬': 'open mailbox with raised flag  ',
  '📭': 'open mailbox with lowered flag  ',
  '📮': 'postbox  ',
  '📯': 'postal horn  ',
  '📜': 'scroll  ',
  '📃': 'page with curl  ',
  '📄': 'page facing up  ',
  '📑': 'bookmark tabs  ',
  '🧾': 'receipt  ',
  '📊': 'bar chart  ',
  '📈': 'chart with upwards trend  ',
  '📉': 'chart with downwards trend  ',
  '🗒️': 'spiral note pad  ',
  '🗓️': 'spiral calendar pad  ',
  '📆': 'tear off calendar  ',
  '📅': 'calendar  ',
  '🗑️': 'wastebasket  ',
  '📇': 'card index  ',
  '🗃️': 'card file box  ',
  '🗳️': 'ballot box with ballot  ',
  '🗄️': 'file cabinet  ',
  '📋': 'clipboard  ',
  '📁': 'file folder  ',
  '📂': 'open file folder  ',
  '🗂️': 'card index dividers  ',
  '🗞️': 'rolled up newspaper  ',
  '📰': 'newspaper  ',
  '📓': 'notebook  ',
  '📔': 'notebook with decorative cover  ',
  '📒': 'ledger  ',
  '📕': 'closed book  ',
  '📗': 'green book  ',
  '📘': 'blue book  ',
  '📙': 'orange book  ',
  '📚': 'books  ',
  '📖': 'open book  ',
  '🔖': 'bookmark  ',
  '🧷': 'safety pin  ',
  '🔗': 'link symbol  ',
  '📎': 'paperclip  ',
  '🖇️': 'linked paperclips  ',
  '📐': 'triangular ruler  ',
  '📏': 'straight ruler  ',
  '🧮': 'abacus  ',
  '📌': 'pushpin  ',
  '📍': 'round pushpin  ',
  '✂️': 'black scissors  ',
  '🖊️': 'lower left ballpoint pen  ',
  '🖋️': 'lower left fountain pen  ',
  '✒️': 'black nib  ',
  '🖌️': 'lower left paintbrush  ',
  '🖍️': 'lower left crayon  ',
  '📝': 'memo  ',
  '✏️': 'pencil  ',
  '🔍': 'left pointing magnifying glass  ',
  '🔎': 'right pointing magnifying glass  ',
  '🔏': 'lock with ink pen  ',
  '🔐': 'closed lock with key  ',
  '🔒': 'lock  ',
  '🔓': 'open lock  ',
  '🧡': 'orange heart  ',
  '💛': 'yellow heart  ',
  '💚': 'green heart  ',
  '💙': 'blue heart  ',
  '🩵': 'light blue heart  ',
  '💜': 'purple heart  ',
  '🖤': 'black heart  ',
  '🩶': 'grey heart  ',
  '🤍': 'white heart  ',
  '🤎': 'brown heart  ',
  '💔': 'broken heart sad love heartbreak broken heart breakup pain ',
  '❤️‍🔥': 'heavy black heart fire  ',
  '❤️‍🩹': 'heavy black heart adhesive bandage  ',
  '❣️': 'heavy heart exclamation mark ornament  ',
  '💕': 'two hearts love hearts romance cute affection ',
  '💞': 'revolving hearts  ',
  '💓': 'beating heart  ',
  '💗': 'growing heart  ',
  '💖': 'sparkling heart love sparkling heart romance cute affection ',
  '💘': 'heart with arrow love cupid heart romance valentine crush ',
  '💝': 'heart with ribbon  ',
  '💟': 'heart decoration  ',
  '☮️': 'peace symbol  ',
  '✝️': 'latin cross  ',
  '☪️': 'star and crescent  ',
  '🕉️': 'om symbol  ',
  '☸️': 'wheel of dharma  ',
  '✡️': 'star of david  ',
  '🔯': 'six pointed star with middle dot  ',
  '🕎': 'menorah with nine branches  ',
  '☯️': 'yin yang  ',
  '☦️': 'orthodox cross  ',
  '🛐': 'place of worship  ',
  '⛎': 'ophiuchus  ',
  '♈': 'aries  ',
  '♉': 'taurus  ',
  '♊': 'gemini  ',
  '♋': 'cancer  ',
  '♌': 'leo  ',
  '♍': 'virgo  ',
  '♎': 'libra  ',
  '♏': 'scorpius  ',
  '♐': 'sagittarius  ',
  '♑': 'capricorn  ',
  '♒': 'aquarius  ',
  '♓': 'pisces  ',
  '🆔': 'squared id  ',
  '⚛️': 'atom symbol  ',
  '🉑': 'circled ideograph accept  ',
  '☢️': 'radioactive sign  ',
  '☣️': 'biohazard sign  ',
  '📴': 'mobile phone off  ',
  '📳': 'vibration mode  ',
  '🈶': 'squared cjk unified ideograph 6709  ',
  '🈚': 'squared cjk unified ideograph 7121  ',
  '🈸': 'squared cjk unified ideograph 7533  ',
  '🈺': 'squared cjk unified ideograph 55b6  ',
  '🈷️': 'squared cjk unified ideograph 6708  ',
  '✴️': 'eight pointed black star  ',
  '🆚': 'squared vs  ',
  '💮': 'white flower  ',
  '🉐': 'circled ideograph advantage  ',
  '㊙️': 'circled ideograph secret  ',
  '㊗️': 'circled ideograph congratulation  ',
  '🈴': 'squared cjk unified ideograph 5408  ',
  '🈵': 'squared cjk unified ideograph 6e80  ',
  '🈹': 'squared cjk unified ideograph 5272  ',
  '🈲': 'squared cjk unified ideograph 7981  ',
  '🅰️': 'negative squared latin capital letter a  ',
  '🅱️': 'negative squared latin capital letter b  ',
  '🆎': 'negative squared ab  ',
  '🆑': 'squared cl  ',
  '🅾️': 'negative squared latin capital letter o  ',
  '🆘': 'squared sos  ',
  '⭕': 'heavy large circle  ',
  '⛔': 'no entry  ',
  '📛': 'name badge  ',
  '🚫': 'no entry sign  ',
  '💯': 'hundred points symbol  ',
  '💢': 'anger symbol  ',
  '🚷': 'no pedestrians  ',
  '🚯': 'do not litter symbol  ',
  '🚳': 'no bicycles  ',
  '🚱': 'non potable water symbol  ',
  '🔞': 'no one under eighteen symbol  ',
  '📵': 'no mobile phones  ',
  '🚭': 'no smoking symbol  ',
  '❗': 'heavy exclamation mark symbol  ',
  '❕': 'white exclamation mark ornament  ',
  '❓': 'black question mark ornament  ',
  '❔': 'white question mark ornament  ',
  '‼️': 'double exclamation mark  ',
  '⁉️': 'exclamation question mark  ',
  '🔅': 'low brightness symbol  ',
  '🔆': 'high brightness symbol  ',
  '〽️': 'part alternation mark  ',
  '⚠️': 'warning sign  ',
  '🚸': 'children crossing  ',
  '🔱': 'trident emblem  ',
  '⚜️': 'fleur de lis  ',
  '🔰': 'japanese symbol for beginner  ',
  '♻️': 'black universal recycling symbol  ',
  '🈯': 'squared cjk unified ideograph 6307  ',
  '💹': 'chart with upwards trend and yen sign  ',
  '❇️': 'sparkle  ',
  '✳️': 'eight spoked asterisk  ',
  '💠': 'diamond shape with a dot inside  ',
  'Ⓜ️': 'circled latin capital letter m  ',
  '🌀': 'cyclone  ',
  '💤': 'sleeping symbol  ',
  '🏧': 'automated teller machine  ',
  '🚾': 'water closet  ',
  '🅿️': 'negative squared latin capital letter p  ',
  '🛗': 'elevator  ',
  '🈳': 'squared cjk unified ideograph 7a7a  ',
  '🈂️': 'squared katakana sa  ',
  '🛂': 'passport control  ',
  '🛃': 'customs  ',
  '🛄': 'baggage claim  ',
  '🛅': 'left luggage  ',
  '🚹': 'mens symbol  ',
  '🚺': 'womens symbol  ',
  '🚼': 'baby symbol  ',
  '⚧️': 'male with stroke and male and female sign  ',
  '🚻': 'restroom  ',
  '🚮': 'put litter in its place symbol  ',
  '🎦': 'cinema  ',
  '📶': 'antenna with bars  ',
  '🈁': 'squared katakana koko  ',
  '🔣': 'input symbol for symbols  ',
  'ℹ️': 'information source  ',
  '🔤': 'input symbol for latin letters  ',
  '🔡': 'input symbol for latin small letters  ',
  '🔠': 'input symbol for latin capital letters  ',
  '🆖': 'squared ng  ',
  '🆗': 'squared ok  ',
  '🆙': 'squared up with exclamation mark  ',
  '🆒': 'squared cool  ',
  '🆕': 'squared new  ',
  '🆓': 'squared free  ',
  '0️⃣': 'digit zero combining enclosing keycap  ',
  '1️⃣': 'digit one combining enclosing keycap  ',
  '2️⃣': 'digit two combining enclosing keycap  ',
  '3️⃣': 'digit three combining enclosing keycap  ',
  '4️⃣': 'digit four combining enclosing keycap  ',
  '5️⃣': 'digit five combining enclosing keycap  ',
  '6️⃣': 'digit six combining enclosing keycap  ',
  '7️⃣': 'digit seven combining enclosing keycap  ',
  '8️⃣': 'digit eight combining enclosing keycap  ',
  '9️⃣': 'digit nine combining enclosing keycap  ',
  '🔟': 'keycap ten  ',
  '🔢': 'input symbol for numbers  ',
  '#️⃣': 'number sign combining enclosing keycap  ',
  '*️⃣': 'asterisk combining enclosing keycap  ',
  '⏏️': 'eject symbol  ',
  '▶️': 'black right pointing triangle  ',
  '⏸️': 'double vertical bar  ',
  '⏯️': 'black right pointing triangle with double vertical bar  ',
  '⏹️': 'black square for stop  ',
  '⏺️': 'black circle for record  ',
  '⏭️': 'black right pointing double triangle with vertical bar  ',
  '⏮️': 'black left pointing double triangle with vertical bar  ',
  '◀️': 'black left pointing triangle  ',
  '🔼': 'up pointing small red triangle  ',
  '🔽': 'down pointing small red triangle  ',
  '➡️': 'black rightwards arrow  ',
  '⬅️': 'leftwards black arrow  ',
  '⬆️': 'upwards black arrow  ',
  '⬇️': 'downwards black arrow  ',
  '↗️': 'north east arrow  ',
  '↘️': 'south east arrow  ',
  '↙️': 'south west arrow  ',
  '↖️': 'north west arrow  ',
  '↕️': 'up down arrow  ',
  '↔️': 'left right arrow  ',
  '↪️': 'rightwards arrow with hook  ',
  '↩️': 'leftwards arrow with hook  ',
  '⤴️': 'arrow pointing rightwards then curving upwards  ',
  '⤵️': 'arrow pointing rightwards then curving downwards  ',
  '🔀': 'twisted rightwards arrows  ',
  '🔁': 'clockwise rightwards and leftwards open circle arrows  ',
  '🔂': 'clockwise rightwards and leftwards open circle arrows with circled one overlay  ',
  '🔄': 'anticlockwise downwards and upwards open circle arrows  ',
  '🔃': 'clockwise downwards and upwards open circle arrows  ',
  '🎵': 'musical note  ',
  '🎶': 'multiple musical notes  ',
  '➕': 'heavy plus sign  ',
  '➖': 'heavy minus sign  ',
  '➗': 'heavy division sign  ',
  '✖️': 'heavy multiplication x  ',
  '🟰': 'heavy equals sign  ',
  '♾️': 'permanent paper sign  ',
  '💲': 'heavy dollar sign  ',
  '💱': 'currency exchange  ',
  '™️': 'trade mark sign  ',
  '©️': 'copyright sign  ',
  '®️': 'registered sign  ',
  '〰️': 'wavy dash  ',
  '➰': 'curly loop  ',
  '➿': 'double curly loop  ',
  '🔚': 'end with leftwards arrow above  ',
  '🔙': 'back with leftwards arrow above  ',
  '🔛': 'on with exclamation mark with left right arrow above  ',
  '🔝': 'top with upwards arrow above  ',
  '🔜': 'soon with rightwards arrow above  ',
  '✔️': 'heavy check mark  ',
  '☑️': 'ballot box with check  ',
  '🔘': 'radio button  ',
  '🔴': 'large red circle  ',
  '🟠': 'large orange circle  ',
  '🟡': 'large yellow circle  ',
  '🟢': 'large green circle  ',
  '🔵': 'large blue circle  ',
  '🟣': 'large purple circle  ',
  '⚫': 'medium black circle  ',
  '⚪': 'medium white circle  ',
  '🟤': 'large brown circle  ',
  '🔺': 'up pointing red triangle  ',
  '🔻': 'down pointing red triangle  ',
  '🔸': 'small orange diamond  ',
  '🔹': 'small blue diamond  ',
  '🔶': 'large orange diamond  ',
  '🔷': 'large blue diamond  ',
  '🔳': 'white square button  ',
  '🔲': 'black square button  ',
  '▪️': 'black small square  ',
  '▫️': 'white small square  ',
  '◾': 'black medium small square  ',
  '◽': 'white medium small square  ',
  '◼️': 'black medium square  ',
  '◻️': 'white medium square  ',
  '🟥': 'large red square  ',
  '🟧': 'large orange square  ',
  '🟨': 'large yellow square  ',
  '🟩': 'large green square  ',
  '🟦': 'large blue square  ',
  '🟪': 'large purple square  ',
  '⬛': 'black large square  ',
  '⬜': 'white large square  ',
  '🟫': 'large brown square  ',
  '🏁': 'chequered flag  ',
  '🚩': 'triangular flag on post  ',
  '🎌': 'crossed flags  ',
  '🏴': 'waving black flag  ',
  '🏳️': 'waving white flag  ',
  '🏳️‍🌈': 'waving white flag rainbow  ',
  '🏳️‍⚧️': 'waving white flag male with stroke and male and female sign  ',
  '🏴‍☠️': 'waving black flag skull and crossbones  ',
  '🇦🇨': 'regional indicator symbol letter a regional indicator symbol letter c  flag ac country nation ascension island',
  '🇦🇩': 'regional indicator symbol letter a regional indicator symbol letter d  flag ad country nation andorra principality of andorra',
  '🇦🇪': 'regional indicator symbol letter a regional indicator symbol letter e  flag ae country nation united arab emirates united arab emirates uae dubai',
  '🇦🇫': 'regional indicator symbol letter a regional indicator symbol letter f  flag af country nation afghanistan islamic republic of afghanistan',
  '🇦🇬': 'regional indicator symbol letter a regional indicator symbol letter g  flag ag country nation antigua and barbuda',
  '🇦🇮': 'regional indicator symbol letter a regional indicator symbol letter i  flag ai country nation anguilla',
  '🇦🇱': 'regional indicator symbol letter a regional indicator symbol letter l  flag al country nation albania republic of albania',
  '🇦🇲': 'regional indicator symbol letter a regional indicator symbol letter m  flag am country nation armenia republic of armenia',
  '🇦🇴': 'regional indicator symbol letter a regional indicator symbol letter o  flag ao country nation angola republic of angola',
  '🇦🇶': 'regional indicator symbol letter a regional indicator symbol letter q  flag aq country nation antarctica',
  '🇦🇷': 'regional indicator symbol letter a regional indicator symbol letter r  flag ar country nation argentina argentine republic',
  '🇦🇸': 'regional indicator symbol letter a regional indicator symbol letter s  flag as country nation american samoa',
  '🇦🇹': 'regional indicator symbol letter a regional indicator symbol letter t  flag at country nation austria republic of austria',
  '🇦🇺': 'regional indicator symbol letter a regional indicator symbol letter u  flag au country nation australia',
  '🇦🇼': 'regional indicator symbol letter a regional indicator symbol letter w  flag aw country nation aruba',
  '🇦🇽': 'regional indicator symbol letter a regional indicator symbol letter x  flag ax country nation åland islands',
  '🇦🇿': 'regional indicator symbol letter a regional indicator symbol letter z  flag az country nation azerbaijan republic of azerbaijan',
  '🇧🇦': 'regional indicator symbol letter b regional indicator symbol letter a  flag ba country nation bosnia and herzegovina republic of bosnia and herzegovina',
  '🇧🇧': 'regional indicator symbol letter b regional indicator symbol letter b  flag bb country nation barbados',
  '🇧🇩': 'regional indicator symbol letter b regional indicator symbol letter d  flag bd country nation bangladesh people\'s republic of bangladesh',
  '🇧🇪': 'regional indicator symbol letter b regional indicator symbol letter e  flag be country nation belgium kingdom of belgium',
  '🇧🇫': 'regional indicator symbol letter b regional indicator symbol letter f  flag bf country nation burkina faso',
  '🇧🇬': 'regional indicator symbol letter b regional indicator symbol letter g  flag bg country nation bulgaria republic of bulgaria',
  '🇧🇭': 'regional indicator symbol letter b regional indicator symbol letter h  flag bh country nation bahrain kingdom of bahrain',
  '🇧🇮': 'regional indicator symbol letter b regional indicator symbol letter i  flag bi country nation burundi republic of burundi',
  '🇧🇯': 'regional indicator symbol letter b regional indicator symbol letter j  flag bj country nation benin republic of benin',
  '🇧🇱': 'regional indicator symbol letter b regional indicator symbol letter l  flag bl country nation saint barthélemy',
  '🇧🇲': 'regional indicator symbol letter b regional indicator symbol letter m  flag bm country nation bermuda',
  '🇧🇳': 'regional indicator symbol letter b regional indicator symbol letter n  flag bn country nation brunei darussalam',
  '🇧🇴': 'regional indicator symbol letter b regional indicator symbol letter o  flag bo country nation bolivia, plurinational state of plurinational state of bolivia bolivia',
  '🇧🇶': 'regional indicator symbol letter b regional indicator symbol letter q  flag bq country nation bonaire, sint eustatius and saba bonaire, sint eustatius and saba',
  '🇧🇷': 'regional indicator symbol letter b regional indicator symbol letter r  flag br country nation brazil federative republic of brazil',
  '🇧🇸': 'regional indicator symbol letter b regional indicator symbol letter s  flag bs country nation bahamas commonwealth of the bahamas',
  '🇧🇹': 'regional indicator symbol letter b regional indicator symbol letter t  flag bt country nation bhutan kingdom of bhutan',
  '🇧🇻': 'regional indicator symbol letter b regional indicator symbol letter v  flag bv country nation bouvet island',
  '🇧🇼': 'regional indicator symbol letter b regional indicator symbol letter w  flag bw country nation botswana republic of botswana',
  '🇧🇾': 'regional indicator symbol letter b regional indicator symbol letter y  flag by country nation belarus republic of belarus',
  '🇧🇿': 'regional indicator symbol letter b regional indicator symbol letter z  flag bz country nation belize',
  '🇨🇦': 'regional indicator symbol letter c regional indicator symbol letter a  flag ca country nation canada',
  '🇨🇨': 'regional indicator symbol letter c regional indicator symbol letter c  flag cc country nation cocos (keeling) islands',
  '🇨🇩': 'regional indicator symbol letter c regional indicator symbol letter d  flag cd country nation congo, the democratic republic of the',
  '🇨🇫': 'regional indicator symbol letter c regional indicator symbol letter f  flag cf country nation central african republic',
  '🇨🇬': 'regional indicator symbol letter c regional indicator symbol letter g  flag cg country nation congo republic of the congo',
  '🇨🇭': 'regional indicator symbol letter c regional indicator symbol letter h  flag ch country nation switzerland swiss confederation',
  '🇨🇮': 'regional indicator symbol letter c regional indicator symbol letter i  flag ci country nation côte d\'ivoire republic of côte d\'ivoire',
  '🇨🇰': 'regional indicator symbol letter c regional indicator symbol letter k  flag ck country nation cook islands',
  '🇨🇱': 'regional indicator symbol letter c regional indicator symbol letter l  flag cl country nation chile republic of chile',
  '🇨🇲': 'regional indicator symbol letter c regional indicator symbol letter m  flag cm country nation cameroon republic of cameroon',
  '🇨🇳': 'regional indicator symbol letter c regional indicator symbol letter n  flag cn country nation china people\'s republic of china china chinese',
  '🇨🇴': 'regional indicator symbol letter c regional indicator symbol letter o  flag co country nation colombia republic of colombia',
  '🇨🇵': 'regional indicator symbol letter c regional indicator symbol letter p  flag cp country nation ',
  '🇨🇷': 'regional indicator symbol letter c regional indicator symbol letter r  flag cr country nation costa rica republic of costa rica',
  '🇨🇺': 'regional indicator symbol letter c regional indicator symbol letter u  flag cu country nation cuba republic of cuba',
  '🇨🇻': 'regional indicator symbol letter c regional indicator symbol letter v  flag cv country nation cabo verde republic of cabo verde',
  '🇨🇼': 'regional indicator symbol letter c regional indicator symbol letter w  flag cw country nation curaçao curaçao',
  '🇨🇽': 'regional indicator symbol letter c regional indicator symbol letter x  flag cx country nation christmas island',
  '🇨🇾': 'regional indicator symbol letter c regional indicator symbol letter y  flag cy country nation cyprus republic of cyprus',
  '🇨🇿': 'regional indicator symbol letter c regional indicator symbol letter z  flag cz country nation czechia czech republic',
  '🇩🇪': 'regional indicator symbol letter d regional indicator symbol letter e  flag de country nation germany federal republic of germany',
  '🇩🇬': 'regional indicator symbol letter d regional indicator symbol letter g  flag dg country nation ',
  '🇩🇯': 'regional indicator symbol letter d regional indicator symbol letter j  flag dj country nation djibouti republic of djibouti',
  '🇩🇰': 'regional indicator symbol letter d regional indicator symbol letter k  flag dk country nation denmark kingdom of denmark',
  '🇩🇲': 'regional indicator symbol letter d regional indicator symbol letter m  flag dm country nation dominica commonwealth of dominica',
  '🇩🇴': 'regional indicator symbol letter d regional indicator symbol letter o  flag do country nation dominican republic',
  '🇩🇿': 'regional indicator symbol letter d regional indicator symbol letter z  flag dz country nation algeria people\'s democratic republic of algeria',
  '🇪🇦': 'regional indicator symbol letter e regional indicator symbol letter a  flag ea country nation ',
  '🇪🇨': 'regional indicator symbol letter e regional indicator symbol letter c  flag ec country nation ecuador republic of ecuador',
  '🇪🇪': 'regional indicator symbol letter e regional indicator symbol letter e  flag ee country nation estonia republic of estonia',
  '🇪🇬': 'regional indicator symbol letter e regional indicator symbol letter g  flag eg country nation egypt arab republic of egypt',
  '🇪🇭': 'regional indicator symbol letter e regional indicator symbol letter h  flag eh country nation western sahara',
  '🇪🇷': 'regional indicator symbol letter e regional indicator symbol letter r  flag er country nation eritrea the state of eritrea',
  '🇪🇸': 'regional indicator symbol letter e regional indicator symbol letter s  flag es country nation spain kingdom of spain',
  '🇪🇹': 'regional indicator symbol letter e regional indicator symbol letter t  flag et country nation ethiopia federal democratic republic of ethiopia',
  '🇪🇺': 'regional indicator symbol letter e regional indicator symbol letter u  flag eu country nation european union',
  '🇫🇮': 'regional indicator symbol letter f regional indicator symbol letter i  flag fi country nation finland republic of finland',
  '🇫🇯': 'regional indicator symbol letter f regional indicator symbol letter j  flag fj country nation fiji republic of fiji',
  '🇫🇰': 'regional indicator symbol letter f regional indicator symbol letter k  flag fk country nation falkland islands (malvinas)',
  '🇫🇲': 'regional indicator symbol letter f regional indicator symbol letter m  flag fm country nation micronesia, federated states of federated states of micronesia',
  '🇫🇴': 'regional indicator symbol letter f regional indicator symbol letter o  flag fo country nation faroe islands',
  '🇫🇷': 'regional indicator symbol letter f regional indicator symbol letter r  flag fr country nation france french republic',
  '🇬🇦': 'regional indicator symbol letter g regional indicator symbol letter a  flag ga country nation gabon gabonese republic',
  '🇬🇧': 'regional indicator symbol letter g regional indicator symbol letter b uk britain united kingdom british england flag country nation flag gb country nation united kingdom united kingdom of great britain and northern ireland united kingdom uk britain british england',
  '🇬🇩': 'regional indicator symbol letter g regional indicator symbol letter d  flag gd country nation grenada',
  '🇬🇪': 'regional indicator symbol letter g regional indicator symbol letter e  flag ge country nation georgia',
  '🇬🇫': 'regional indicator symbol letter g regional indicator symbol letter f  flag gf country nation french guiana',
  '🇬🇬': 'regional indicator symbol letter g regional indicator symbol letter g  flag gg country nation guernsey',
  '🇬🇭': 'regional indicator symbol letter g regional indicator symbol letter h  flag gh country nation ghana republic of ghana',
  '🇬🇮': 'regional indicator symbol letter g regional indicator symbol letter i  flag gi country nation gibraltar',
  '🇬🇱': 'regional indicator symbol letter g regional indicator symbol letter l  flag gl country nation greenland',
  '🇬🇲': 'regional indicator symbol letter g regional indicator symbol letter m  flag gm country nation gambia republic of the gambia',
  '🇬🇳': 'regional indicator symbol letter g regional indicator symbol letter n  flag gn country nation guinea republic of guinea',
  '🇬🇵': 'regional indicator symbol letter g regional indicator symbol letter p  flag gp country nation guadeloupe',
  '🇬🇶': 'regional indicator symbol letter g regional indicator symbol letter q  flag gq country nation equatorial guinea republic of equatorial guinea',
  '🇬🇷': 'regional indicator symbol letter g regional indicator symbol letter r  flag gr country nation greece hellenic republic',
  '🇬🇸': 'regional indicator symbol letter g regional indicator symbol letter s  flag gs country nation south georgia and the south sandwich islands',
  '🇬🇹': 'regional indicator symbol letter g regional indicator symbol letter t  flag gt country nation guatemala republic of guatemala',
  '🇬🇺': 'regional indicator symbol letter g regional indicator symbol letter u  flag gu country nation guam',
  '🇬🇼': 'regional indicator symbol letter g regional indicator symbol letter w  flag gw country nation guinea-bissau republic of guinea-bissau',
  '🇬🇾': 'regional indicator symbol letter g regional indicator symbol letter y  flag gy country nation guyana republic of guyana',
  '🇭🇰': 'regional indicator symbol letter h regional indicator symbol letter k  flag hk country nation hong kong hong kong special administrative region of china',
  '🇭🇲': 'regional indicator symbol letter h regional indicator symbol letter m  flag hm country nation heard island and mcdonald islands',
  '🇭🇳': 'regional indicator symbol letter h regional indicator symbol letter n  flag hn country nation honduras republic of honduras',
  '🇭🇷': 'regional indicator symbol letter h regional indicator symbol letter r  flag hr country nation croatia republic of croatia',
  '🇭🇹': 'regional indicator symbol letter h regional indicator symbol letter t  flag ht country nation haiti republic of haiti',
  '🇭🇺': 'regional indicator symbol letter h regional indicator symbol letter u  flag hu country nation hungary hungary',
  '🇮🇨': 'regional indicator symbol letter i regional indicator symbol letter c  flag ic country nation ',
  '🇮🇩': 'regional indicator symbol letter i regional indicator symbol letter d  flag id country nation indonesia republic of indonesia',
  '🇮🇪': 'regional indicator symbol letter i regional indicator symbol letter e  flag ie country nation ireland',
  '🇮🇱': 'regional indicator symbol letter i regional indicator symbol letter l  flag il country nation israel state of israel',
  '🇮🇲': 'regional indicator symbol letter i regional indicator symbol letter m  flag im country nation isle of man',
  '🇮🇳': 'regional indicator symbol letter i regional indicator symbol letter n india indian flag nation country bharat hindustan flag in country nation india republic of india india indian bharat hindustan',
  '🇮🇴': 'regional indicator symbol letter i regional indicator symbol letter o  flag io country nation british indian ocean territory',
  '🇮🇶': 'regional indicator symbol letter i regional indicator symbol letter q  flag iq country nation iraq republic of iraq',
  '🇮🇷': 'regional indicator symbol letter i regional indicator symbol letter r  flag ir country nation iran, islamic republic of islamic republic of iran iran',
  '🇮🇸': 'regional indicator symbol letter i regional indicator symbol letter s  flag is country nation iceland republic of iceland',
  '🇮🇹': 'regional indicator symbol letter i regional indicator symbol letter t  flag it country nation italy italian republic',
  '🇯🇪': 'regional indicator symbol letter j regional indicator symbol letter e  flag je country nation jersey',
  '🇯🇲': 'regional indicator symbol letter j regional indicator symbol letter m  flag jm country nation jamaica',
  '🇯🇴': 'regional indicator symbol letter j regional indicator symbol letter o  flag jo country nation jordan hashemite kingdom of jordan',
  '🇯🇵': 'regional indicator symbol letter j regional indicator symbol letter p  flag jp country nation japan japan japanese',
  '🇰🇪': 'regional indicator symbol letter k regional indicator symbol letter e  flag ke country nation kenya republic of kenya',
  '🇰🇬': 'regional indicator symbol letter k regional indicator symbol letter g  flag kg country nation kyrgyzstan kyrgyz republic',
  '🇰🇭': 'regional indicator symbol letter k regional indicator symbol letter h  flag kh country nation cambodia kingdom of cambodia',
  '🇰🇮': 'regional indicator symbol letter k regional indicator symbol letter i  flag ki country nation kiribati republic of kiribati',
  '🇰🇲': 'regional indicator symbol letter k regional indicator symbol letter m  flag km country nation comoros union of the comoros',
  '🇰🇳': 'regional indicator symbol letter k regional indicator symbol letter n  flag kn country nation saint kitts and nevis',
  '🇰🇵': 'regional indicator symbol letter k regional indicator symbol letter p  flag kp country nation korea, democratic people\'s republic of democratic people\'s republic of korea north korea north korea',
  '🇰🇷': 'regional indicator symbol letter k regional indicator symbol letter r  flag kr country nation korea, republic of south korea south korea korea',
  '🇰🇼': 'regional indicator symbol letter k regional indicator symbol letter w  flag kw country nation kuwait state of kuwait',
  '🇰🇾': 'regional indicator symbol letter k regional indicator symbol letter y  flag ky country nation cayman islands',
  '🇰🇿': 'regional indicator symbol letter k regional indicator symbol letter z  flag kz country nation kazakhstan republic of kazakhstan',
  '🇱🇦': 'regional indicator symbol letter l regional indicator symbol letter a  flag la country nation lao people\'s democratic republic laos',
  '🇱🇧': 'regional indicator symbol letter l regional indicator symbol letter b  flag lb country nation lebanon lebanese republic',
  '🇱🇨': 'regional indicator symbol letter l regional indicator symbol letter c  flag lc country nation saint lucia',
  '🇱🇮': 'regional indicator symbol letter l regional indicator symbol letter i  flag li country nation liechtenstein principality of liechtenstein',
  '🇱🇰': 'regional indicator symbol letter l regional indicator symbol letter k  flag lk country nation sri lanka democratic socialist republic of sri lanka',
  '🇱🇷': 'regional indicator symbol letter l regional indicator symbol letter r  flag lr country nation liberia republic of liberia',
  '🇱🇸': 'regional indicator symbol letter l regional indicator symbol letter s  flag ls country nation lesotho kingdom of lesotho',
  '🇱🇹': 'regional indicator symbol letter l regional indicator symbol letter t  flag lt country nation lithuania republic of lithuania',
  '🇱🇺': 'regional indicator symbol letter l regional indicator symbol letter u  flag lu country nation luxembourg grand duchy of luxembourg',
  '🇱🇻': 'regional indicator symbol letter l regional indicator symbol letter v  flag lv country nation latvia republic of latvia',
  '🇱🇾': 'regional indicator symbol letter l regional indicator symbol letter y  flag ly country nation libya libya',
  '🇲🇦': 'regional indicator symbol letter m regional indicator symbol letter a  flag ma country nation morocco kingdom of morocco',
  '🇲🇨': 'regional indicator symbol letter m regional indicator symbol letter c  flag mc country nation monaco principality of monaco',
  '🇲🇩': 'regional indicator symbol letter m regional indicator symbol letter d  flag md country nation moldova, republic of republic of moldova moldova',
  '🇲🇪': 'regional indicator symbol letter m regional indicator symbol letter e  flag me country nation montenegro montenegro',
  '🇲🇫': 'regional indicator symbol letter m regional indicator symbol letter f  flag mf country nation saint martin (french part)',
  '🇲🇬': 'regional indicator symbol letter m regional indicator symbol letter g  flag mg country nation madagascar republic of madagascar',
  '🇲🇭': 'regional indicator symbol letter m regional indicator symbol letter h  flag mh country nation marshall islands republic of the marshall islands',
  '🇲🇰': 'regional indicator symbol letter m regional indicator symbol letter k  flag mk country nation north macedonia republic of north macedonia',
  '🇲🇱': 'regional indicator symbol letter m regional indicator symbol letter l  flag ml country nation mali republic of mali',
  '🇲🇲': 'regional indicator symbol letter m regional indicator symbol letter m  flag mm country nation myanmar republic of myanmar',
  '🇲🇳': 'regional indicator symbol letter m regional indicator symbol letter n  flag mn country nation mongolia',
  '🇲🇴': 'regional indicator symbol letter m regional indicator symbol letter o  flag mo country nation macao macao special administrative region of china',
  '🇲🇵': 'regional indicator symbol letter m regional indicator symbol letter p  flag mp country nation northern mariana islands commonwealth of the northern mariana islands',
  '🇲🇶': 'regional indicator symbol letter m regional indicator symbol letter q  flag mq country nation martinique',
  '🇲🇷': 'regional indicator symbol letter m regional indicator symbol letter r  flag mr country nation mauritania islamic republic of mauritania',
  '🇲🇸': 'regional indicator symbol letter m regional indicator symbol letter s  flag ms country nation montserrat',
  '🇲🇹': 'regional indicator symbol letter m regional indicator symbol letter t  flag mt country nation malta republic of malta',
  '🇲🇺': 'regional indicator symbol letter m regional indicator symbol letter u  flag mu country nation mauritius republic of mauritius',
  '🇲🇻': 'regional indicator symbol letter m regional indicator symbol letter v  flag mv country nation maldives republic of maldives',
  '🇲🇼': 'regional indicator symbol letter m regional indicator symbol letter w  flag mw country nation malawi republic of malawi',
  '🇲🇽': 'regional indicator symbol letter m regional indicator symbol letter x  flag mx country nation mexico united mexican states',
  '🇲🇾': 'regional indicator symbol letter m regional indicator symbol letter y  flag my country nation malaysia',
  '🇲🇿': 'regional indicator symbol letter m regional indicator symbol letter z  flag mz country nation mozambique republic of mozambique',
  '🇳🇦': 'regional indicator symbol letter n regional indicator symbol letter a  flag na country nation namibia republic of namibia',
  '🇳🇨': 'regional indicator symbol letter n regional indicator symbol letter c  flag nc country nation new caledonia',
  '🇳🇪': 'regional indicator symbol letter n regional indicator symbol letter e  flag ne country nation niger republic of the niger',
  '🇳🇫': 'regional indicator symbol letter n regional indicator symbol letter f  flag nf country nation norfolk island',
  '🇳🇬': 'regional indicator symbol letter n regional indicator symbol letter g  flag ng country nation nigeria federal republic of nigeria',
  '🇳🇮': 'regional indicator symbol letter n regional indicator symbol letter i  flag ni country nation nicaragua republic of nicaragua',
  '🇳🇱': 'regional indicator symbol letter n regional indicator symbol letter l  flag nl country nation netherlands kingdom of the netherlands',
  '🇳🇴': 'regional indicator symbol letter n regional indicator symbol letter o  flag no country nation norway kingdom of norway',
  '🇳🇵': 'regional indicator symbol letter n regional indicator symbol letter p  flag np country nation nepal federal democratic republic of nepal',
  '🇳🇷': 'regional indicator symbol letter n regional indicator symbol letter r  flag nr country nation nauru republic of nauru',
  '🇳🇺': 'regional indicator symbol letter n regional indicator symbol letter u  flag nu country nation niue niue',
  '🇳🇿': 'regional indicator symbol letter n regional indicator symbol letter z  flag nz country nation new zealand',
  '🇴🇲': 'regional indicator symbol letter o regional indicator symbol letter m  flag om country nation oman sultanate of oman',
  '🇵🇦': 'regional indicator symbol letter p regional indicator symbol letter a  flag pa country nation panama republic of panama',
  '🇵🇪': 'regional indicator symbol letter p regional indicator symbol letter e  flag pe country nation peru republic of peru',
  '🇵🇫': 'regional indicator symbol letter p regional indicator symbol letter f  flag pf country nation french polynesia',
  '🇵🇬': 'regional indicator symbol letter p regional indicator symbol letter g  flag pg country nation papua new guinea independent state of papua new guinea',
  '🇵🇭': 'regional indicator symbol letter p regional indicator symbol letter h  flag ph country nation philippines republic of the philippines',
  '🇵🇰': 'regional indicator symbol letter p regional indicator symbol letter k  flag pk country nation pakistan islamic republic of pakistan',
  '🇵🇱': 'regional indicator symbol letter p regional indicator symbol letter l  flag pl country nation poland republic of poland',
  '🇵🇲': 'regional indicator symbol letter p regional indicator symbol letter m  flag pm country nation saint pierre and miquelon',
  '🇵🇳': 'regional indicator symbol letter p regional indicator symbol letter n  flag pn country nation pitcairn',
  '🇵🇷': 'regional indicator symbol letter p regional indicator symbol letter r  flag pr country nation puerto rico',
  '🇵🇸': 'regional indicator symbol letter p regional indicator symbol letter s  flag ps country nation palestine, state of the state of palestine',
  '🇵🇹': 'regional indicator symbol letter p regional indicator symbol letter t  flag pt country nation portugal portuguese republic',
  '🇵🇼': 'regional indicator symbol letter p regional indicator symbol letter w  flag pw country nation palau republic of palau',
  '🇵🇾': 'regional indicator symbol letter p regional indicator symbol letter y  flag py country nation paraguay republic of paraguay',
  '🇶🇦': 'regional indicator symbol letter q regional indicator symbol letter a  flag qa country nation qatar state of qatar',
  '🇷🇪': 'regional indicator symbol letter r regional indicator symbol letter e  flag re country nation réunion',
  '🇷🇴': 'regional indicator symbol letter r regional indicator symbol letter o  flag ro country nation romania',
  '🇷🇸': 'regional indicator symbol letter r regional indicator symbol letter s  flag rs country nation serbia republic of serbia',
  '🇷🇺': 'regional indicator symbol letter r regional indicator symbol letter u  flag ru country nation russian federation russia',
  '🇷🇼': 'regional indicator symbol letter r regional indicator symbol letter w  flag rw country nation rwanda rwandese republic',
  '🇸🇦': 'regional indicator symbol letter s regional indicator symbol letter a  flag sa country nation saudi arabia kingdom of saudi arabia',
  '🇸🇧': 'regional indicator symbol letter s regional indicator symbol letter b  flag sb country nation solomon islands',
  '🇸🇨': 'regional indicator symbol letter s regional indicator symbol letter c  flag sc country nation seychelles republic of seychelles',
  '🇸🇩': 'regional indicator symbol letter s regional indicator symbol letter d  flag sd country nation sudan republic of the sudan',
  '🇸🇪': 'regional indicator symbol letter s regional indicator symbol letter e  flag se country nation sweden kingdom of sweden',
  '🇸🇬': 'regional indicator symbol letter s regional indicator symbol letter g  flag sg country nation singapore republic of singapore',
  '🇸🇭': 'regional indicator symbol letter s regional indicator symbol letter h  flag sh country nation saint helena, ascension and tristan da cunha',
  '🇸🇮': 'regional indicator symbol letter s regional indicator symbol letter i  flag si country nation slovenia republic of slovenia',
  '🇸🇯': 'regional indicator symbol letter s regional indicator symbol letter j  flag sj country nation svalbard and jan mayen',
  '🇸🇰': 'regional indicator symbol letter s regional indicator symbol letter k  flag sk country nation slovakia slovak republic',
  '🇸🇱': 'regional indicator symbol letter s regional indicator symbol letter l  flag sl country nation sierra leone republic of sierra leone',
  '🇸🇲': 'regional indicator symbol letter s regional indicator symbol letter m  flag sm country nation san marino republic of san marino',
  '🇸🇳': 'regional indicator symbol letter s regional indicator symbol letter n  flag sn country nation senegal republic of senegal',
  '🇸🇴': 'regional indicator symbol letter s regional indicator symbol letter o  flag so country nation somalia federal republic of somalia',
  '🇸🇷': 'regional indicator symbol letter s regional indicator symbol letter r  flag sr country nation suriname republic of suriname',
  '🇸🇸': 'regional indicator symbol letter s regional indicator symbol letter s  flag ss country nation south sudan republic of south sudan',
  '🇸🇹': 'regional indicator symbol letter s regional indicator symbol letter t  flag st country nation sao tome and principe democratic republic of sao tome and principe',
  '🇸🇻': 'regional indicator symbol letter s regional indicator symbol letter v  flag sv country nation el salvador republic of el salvador',
  '🇸🇽': 'regional indicator symbol letter s regional indicator symbol letter x  flag sx country nation sint maarten (dutch part) sint maarten (dutch part)',
  '🇸🇾': 'regional indicator symbol letter s regional indicator symbol letter y  flag sy country nation syrian arab republic syria',
  '🇸🇿': 'regional indicator symbol letter s regional indicator symbol letter z  flag sz country nation eswatini kingdom of eswatini',
  '🇹🇦': 'regional indicator symbol letter t regional indicator symbol letter a  flag ta country nation tristan da cunha',
  '🇹🇨': 'regional indicator symbol letter t regional indicator symbol letter c  flag tc country nation turks and caicos islands',
  '🇹🇩': 'regional indicator symbol letter t regional indicator symbol letter d  flag td country nation chad republic of chad',
  '🇹🇫': 'regional indicator symbol letter t regional indicator symbol letter f  flag tf country nation french southern territories',
  '🇹🇬': 'regional indicator symbol letter t regional indicator symbol letter g  flag tg country nation togo togolese republic',
  '🇹🇭': 'regional indicator symbol letter t regional indicator symbol letter h  flag th country nation thailand kingdom of thailand',
  '🇹🇯': 'regional indicator symbol letter t regional indicator symbol letter j  flag tj country nation tajikistan republic of tajikistan',
  '🇹🇰': 'regional indicator symbol letter t regional indicator symbol letter k  flag tk country nation tokelau',
  '🇹🇱': 'regional indicator symbol letter t regional indicator symbol letter l  flag tl country nation timor-leste democratic republic of timor-leste',
  '🇹🇲': 'regional indicator symbol letter t regional indicator symbol letter m  flag tm country nation turkmenistan',
  '🇹🇳': 'regional indicator symbol letter t regional indicator symbol letter n  flag tn country nation tunisia republic of tunisia',
  '🇹🇴': 'regional indicator symbol letter t regional indicator symbol letter o  flag to country nation tonga kingdom of tonga',
  '🇹🇷': 'regional indicator symbol letter t regional indicator symbol letter r  flag tr country nation türkiye republic of türkiye',
  '🇹🇹': 'regional indicator symbol letter t regional indicator symbol letter t  flag tt country nation trinidad and tobago republic of trinidad and tobago',
  '🇹🇻': 'regional indicator symbol letter t regional indicator symbol letter v  flag tv country nation tuvalu',
  '🇹🇼': 'regional indicator symbol letter t regional indicator symbol letter w  flag tw country nation taiwan, province of china taiwan, province of china taiwan',
  '🇹🇿': 'regional indicator symbol letter t regional indicator symbol letter z  flag tz country nation tanzania, united republic of united republic of tanzania tanzania',
  '🇺🇦': 'regional indicator symbol letter u regional indicator symbol letter a  flag ua country nation ukraine',
  '🇺🇬': 'regional indicator symbol letter u regional indicator symbol letter g  flag ug country nation uganda republic of uganda',
  '🇺🇲': 'regional indicator symbol letter u regional indicator symbol letter m  flag um country nation united states minor outlying islands',
  '🇺🇳': 'regional indicator symbol letter u regional indicator symbol letter n  flag un country nation united nations',
  '🇺🇸': 'regional indicator symbol letter u regional indicator symbol letter s usa america united states american flag country nation flag us country nation united states united states of america united states usa america american',
  '🇺🇾': 'regional indicator symbol letter u regional indicator symbol letter y  flag uy country nation uruguay eastern republic of uruguay',
  '🇺🇿': 'regional indicator symbol letter u regional indicator symbol letter z  flag uz country nation uzbekistan republic of uzbekistan',
  '🇻🇦': 'regional indicator symbol letter v regional indicator symbol letter a  flag va country nation holy see (vatican city state)',
  '🇻🇨': 'regional indicator symbol letter v regional indicator symbol letter c  flag vc country nation saint vincent and the grenadines',
  '🇻🇪': 'regional indicator symbol letter v regional indicator symbol letter e  flag ve country nation venezuela, bolivarian republic of bolivarian republic of venezuela venezuela',
  '🇻🇬': 'regional indicator symbol letter v regional indicator symbol letter g  flag vg country nation virgin islands, british british virgin islands',
  '🇻🇮': 'regional indicator symbol letter v regional indicator symbol letter i  flag vi country nation virgin islands, u.s. virgin islands of the united states',
  '🇻🇳': 'regional indicator symbol letter v regional indicator symbol letter n  flag vn country nation viet nam socialist republic of viet nam vietnam',
  '🇻🇺': 'regional indicator symbol letter v regional indicator symbol letter u  flag vu country nation vanuatu republic of vanuatu',
  '🇼🇫': 'regional indicator symbol letter w regional indicator symbol letter f  flag wf country nation wallis and futuna',
  '🇼🇸': 'regional indicator symbol letter w regional indicator symbol letter s  flag ws country nation samoa independent state of samoa',
  '🇽🇰': 'regional indicator symbol letter x regional indicator symbol letter k  flag xk country nation kosovo',
  '🇾🇪': 'regional indicator symbol letter y regional indicator symbol letter e  flag ye country nation yemen republic of yemen',
  '🇾🇹': 'regional indicator symbol letter y regional indicator symbol letter t  flag yt country nation mayotte',
  '🇿🇦': 'regional indicator symbol letter z regional indicator symbol letter a  flag za country nation south africa republic of south africa',
  '🇿🇲': 'regional indicator symbol letter z regional indicator symbol letter m  flag zm country nation zambia republic of zambia',
  '🇿🇼': 'regional indicator symbol letter z regional indicator symbol letter w  flag zw country nation zimbabwe republic of zimbabwe',
  '✨': 'sparkles ',
  '✋': 'raised hand ',
  '✌': 'victory hand ',
  '☝': 'white up pointing index ',
  '✊': 'raised fist ',
  '✍': 'writing hand ',
  '⛷': 'skier ',
  '⛹': 'person with ball ',
  '💐': 'bouquet bouquet flowers love nature gift wedding romance ',
  '🌸': 'cherry blossom cherry blossom flower pink spring nature cute ',
  '🪷': 'lotus lotus flower calm peace nature india buddhism ',
  '🌹': 'rose rose flower love romance valentine ',
  '🥀': 'wilted flower wilted flower sad heartbreak dead rose ',
  '🌺': 'hibiscus hibiscus flower tropical nature ',
  '🌻': 'sunflower sunflower flower sun nature ',
  '🌼': 'blossom blossom flower daisy nature ',
  '🌷': 'tulip tulip flower spring nature ',
  '🪻': 'hyacinth hyacinth flower purple nature ',
  '☘️': 'shamrock shamrock lucky leaf ireland ',
  '🍀': 'four leaf clover four leaf clover luck lucky leaf ',
  '🌿': 'herb herb leaf green plant nature ',
  '🌱': 'seedling seedling plant grow nature green ',
  '🌲': 'evergreen tree evergreen tree forest nature ',
  '🌳': 'deciduous tree tree forest nature ',
  '🌴': 'palm tree palm tree beach tropical ',
  '🌵': 'cactus cactus desert plant ',
  '🌾': 'ear of rice rice crop plant farm ',
  '🍁': 'maple leaf maple leaf autumn fall canada ',
  '🍂': 'fallen leaf fallen leaf autumn fall ',
  '🍃': 'leaf fluttering in wind leaf fluttering wind nature ',
  '🪴': 'potted plant potted plant house plant nature ',
  '🪹': 'empty nest empty nest bird nature ',
  '🪺': 'nest with eggs nest eggs bird nature ',
  '❄️': 'snowflake snowflake snow cold winter ice ',
  '☃️': 'snowman snowman snow winter cold ',
  '⛄': 'snowman without snow snowman snow winter cold ',
  '🌡️': 'thermometer thermometer temperature fever hot cold ',
  '🌊': 'water wave water wave ocean sea ',
  '💨': 'dash symbol wind dash fast air ',
  '🌬️': 'wind blowing face wind face air blow ',
  '🌪️': 'cloud with tornado tornado storm wind ',
  '⚡': 'high voltage sign ',
  '☔': 'umbrella with rain drops umbrella rain ',
  '☂️': 'umbrella umbrella rain ',
  '🌈': 'rainbow rainbow color pride ',
  '💧': 'droplet droplet water tear ',
  '☁️': 'cloud cloud weather ',
  '🌨️': 'cloud with snow cloud snow weather ',
  '🌧️': 'cloud with rain cloud rain weather ',
  '⛈️': 'thunder cloud and rain thunderstorm rain lightning ',
  '🌩️': 'cloud with lightning lightning cloud storm ',
  '🌦️': 'white sun behind cloud with rain sun behind rain cloud weather ',
  '⛅': 'sun behind cloud sun behind cloud weather ',
  '🌤️': 'white sun with small cloud sun small cloud weather ',
  '☀️': 'black sun with rays sun sunny hot day ',
  '🌞': 'sun with face sun face sunny happy ',
  '🌝': 'full moon with face full moon face night ',
  '🌚': 'new moon with face new moon face night dark ',
  '🌛': 'first quarter moon with face first quarter moon face night ',
  '🌜': 'last quarter moon with face last quarter moon face night ',
  '🌙': 'crescent moon crescent moon night sleep ',
  '⭐': 'white medium star star favorite night ',
  '🌟': 'glowing star glowing star sparkle ',
  '🪐': 'ringed planet ringed planet saturn space ',
  '🌌': 'milky way milky way galaxy space night ',
  '☄️': 'comet comet space meteor ',
  '🌑': 'new moon symbol ',
  '🌒': 'waxing crescent moon symbol ',
  '🌓': 'first quarter moon symbol ',
  '🌔': 'waxing gibbous moon symbol ',
  '🌕': 'full moon symbol ',
  '🌖': 'waning gibbous moon symbol ',
  '🌗': 'last quarter moon symbol ',
  '🌘': 'waning crescent moon symbol ',
  '☕': 'hot beverage ',
  '⛪': 'church ',
  '⛲': 'fountain ',
  '⛺': 'tent ',
  '⛽': 'fuel pump ',
  '⚓': 'anchor ',
  '⛵': 'sailboat ',
  '⛳': 'flag in hole ',
  '⏰': 'alarm clock ',
  '❌': 'cross mark ',
  '✅': 'white heavy check mark ',
  '❎': 'negative squared cross mark ',
  '♿': 'wheelchair symbol ',
  '⏩': 'black right-pointing double triangle ',
  '⏪': 'black left-pointing double triangle ',
  '⏫': 'black up-pointing double triangle ',
  '⏬': 'black down-pointing double triangle ',
};

const Map<String, List<String>> emojiRelatedSearchWords = {
  'party': ['celebration', 'celebrate', 'birthday', 'congrats', 'congratulations', 'confetti', 'cake', 'balloon', 'gift', 'disco', 'dance', 'music', 'festival', 'fun', 'cheers'],
  'celebration': ['party', 'birthday', 'confetti', 'gift', 'balloon', 'cake', 'festival', 'cheers'],
  'birthday': ['party', 'cake', 'gift', 'balloon', 'celebration', 'confetti'],
  'love': ['heart', 'romance', 'romantic', 'crush', 'kiss', 'couple', 'valentine', 'care', 'affection', 'cute'],
  'romance': ['love', 'heart', 'kiss', 'couple', 'valentine', 'rose'],
  'sad': ['cry', 'crying', 'tears', 'pain', 'lonely', 'depressed', 'broken', 'heartbreak', 'upset', 'emotional'],
  'happy': ['smile', 'laugh', 'joy', 'excited', 'funny', 'lol', 'lmao'],
  'angry': ['mad', 'rage', 'annoyed', 'furious', 'pissed'],
  'money': ['cash', 'rich', 'payment', 'bank', 'card', 'coin', 'wealth', 'price', 'diamond'],
  'fire': ['hot', 'lit', 'flame', 'burn', 'hype'],
  'dead': ['death', 'skull', 'grave', 'coffin', 'rip', 'skeleton'],
  'india': ['indian', 'bharat', 'hindustan', 'flag', 'country', 'nation'],
  'liberty': ['statue', 'new', 'york', 'usa', 'america', 'landmark', 'monument'],
  'sigma': ['meme', 'moyai', 'moai', 'stone', 'face', 'mewing', 'mog', 'bro', 'savage', 'attitude'],
  'music': ['song', 'audio', 'sound', 'sing', 'instrument', 'guitar', 'piano', 'microphone', 'headphones'],
  'game': ['gaming', 'controller', 'play', 'arcade', 'dice', 'puzzle', 'chess'],
  'gaming': ['game', 'controller', 'play', 'arcade'],
  'tech': ['phone', 'computer', 'laptop', 'keyboard', 'internet', 'wifi', 'battery', 'lock', 'camera'],
  'travel': ['trip', 'destination', 'place', 'vehicle', 'airplane', 'train', 'car', 'bus', 'map', 'hotel'],
  'food': ['eat', 'hungry', 'meal', 'snack', 'restaurant', 'fruit', 'vegetable', 'cake', 'pizza', 'burger'],
  'sleep': ['sleepy', 'tired', 'bed', 'night', 'bored', 'rest'],
  'sick': ['ill', 'fever', 'hospital', 'medicine', 'vomit', 'doctor'],
  'study': ['book', 'school', 'student', 'pen', 'pencil', 'notebook', 'brain'],
  'work': ['office', 'briefcase', 'computer', 'tool', 'worker'],
  'photo': ['camera', 'picture', 'image', 'gallery'],
  'video': ['movie', 'camera', 'film', 'cinema'],
  'car': ['vehicle', 'auto', 'taxi', 'truck', 'transport', 'travel'],
  'bike': ['motorcycle', 'scooter', 'cycle', 'vehicle'],
  'nature': ['animal', 'plant', 'flower', 'tree', 'leaf', 'mountain', 'river', 'weather', 'earth', 'forest', 'green'],
  'flower': ['rose', 'bouquet', 'blossom', 'lotus', 'tulip', 'sunflower', 'nature', 'love'],
  'weather': ['sun', 'cloud', 'rain', 'storm', 'snow', 'wind', 'thunder', 'lightning', 'umbrella'],
  'space': ['planet', 'rocket', 'moon', 'star', 'galaxy', 'comet', 'alien'],
  'celebrate': ['party', 'birthday', 'confetti', 'gift', 'balloon', 'cake', 'festival', 'cheers'],
  'congrats': ['party', 'celebration', 'confetti', 'trophy', 'medal', 'clap', 'gift'],
  'gift': ['present', 'birthday', 'party', 'surprise', 'box', 'ribbon'],
  'flag': ['country', 'nation', 'india', 'usa', 'uk', 'japan', 'pirate', 'pride'],
  'country': ['flag', 'nation', 'india', 'usa', 'america', 'japan', 'china', 'uk'],
  'vehicle': ['car', 'bus', 'train', 'bike', 'motorcycle', 'truck', 'taxi', 'transport', 'travel'],
  'building': ['house', 'home', 'hospital', 'school', 'bank', 'hotel', 'temple', 'church', 'mosque', 'castle'],
  'tool': ['hammer', 'wrench', 'screwdriver', 'gear', 'repair', 'work', 'build'],
  'object': ['tool', 'phone', 'computer', 'money', 'mail', 'book', 'lock'],
  'symbol': ['sign', 'arrow', 'heart', 'warning', 'check', 'cross', 'number', 'shape'],

};